name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test

      - name: Build
        run: npm run build
        if: github.ref_type == 'tag' || github.ref_name == 'main'

      - name: Prepare publish
        run: |
          cp -r dist/* ./docs/ && \
          sed -i -e 's/="\//="\/xuan-paper\//g' docs/index.html && \
          sed -i -e 's/:\s*"\//:"\/xuan-paper\//g' docs/manifest.webmanifest
        if: github.ref_type == 'tag' || github.ref_name == 'main'

      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Publish sample"
        if: github.ref_type == 'tag' || github.ref_name == 'main'

      - name: Archive
        run: zip -r xuan-paper_${{ github.ref_name }}.zip dist src/xuan-paper tools
        if: github.ref_type == 'tag'

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: xuan-paper_${{ github.ref_name }}.zip
